package org.turter.patrocl.domain.model.enums

enum class SourceDataType {
    COMPANY_STATION_DISHES,
    COMPANY_DISHES,

    COMPANY_CATEGORIES,

    COMPANY_STATION_MODIFIERS,
    COMPANY_MODIFIERS,

    COMPANY_MODIFIERS_GROUPS,

    COMPANY_MODIFIERS_SCHEMES,

    COMPANY_MODIFIERS_SCHEMES_DETAILS,

    COMPANY_HALLS,

    COMPANY_TABLES,

    COMPANY_ORDER_ITEM_VOIDS,

    COMPANY_WAITERS,
}